// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant_Reservation_System.Data;

#nullable disable

namespace Restaurant_Reservation_System.Data.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20260405075346_final_mig")]
    partial class final_mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main Dishes",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drinks",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Traditional Meals",
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wine & Drinks",
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Garden Specials",
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Desserts",
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Lobio & Beans",
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "Extras",
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Khachapuri",
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "Drinks",
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "Georgian Classics",
                            RestaurantId = 6
                        },
                        new
                        {
                            Id = 12,
                            Name = "Drinks",
                            RestaurantId = 6
                        });
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvaiable")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvaiable = true,
                            MenuId = 1,
                            Name = "Chashushuli",
                            Price = 18.5m
                        },
                        new
                        {
                            Id = 2,
                            IsAvaiable = true,
                            MenuId = 1,
                            Name = "Ojakhuri",
                            Price = 16.0m
                        },
                        new
                        {
                            Id = 3,
                            IsAvaiable = true,
                            MenuId = 2,
                            Name = "Red Wine",
                            Price = 12.0m
                        },
                        new
                        {
                            Id = 4,
                            IsAvaiable = true,
                            MenuId = 2,
                            Name = "Craft Beer",
                            Price = 8.5m
                        },
                        new
                        {
                            Id = 5,
                            IsAvaiable = true,
                            MenuId = 3,
                            Name = "Kharcho",
                            Price = 20.0m
                        },
                        new
                        {
                            Id = 6,
                            IsAvaiable = true,
                            MenuId = 3,
                            Name = "Chkmeruli",
                            Price = 19.5m
                        },
                        new
                        {
                            Id = 7,
                            IsAvaiable = true,
                            MenuId = 4,
                            Name = "White Wine",
                            Price = 13.0m
                        },
                        new
                        {
                            Id = 8,
                            IsAvaiable = true,
                            MenuId = 4,
                            Name = "Mineral Water",
                            Price = 3.0m
                        },
                        new
                        {
                            Id = 9,
                            IsAvaiable = true,
                            MenuId = 5,
                            Name = "Mtsvadi",
                            Price = 17.0m
                        },
                        new
                        {
                            Id = 10,
                            IsAvaiable = true,
                            MenuId = 5,
                            Name = "Badrijani Nigvzit",
                            Price = 11.0m
                        },
                        new
                        {
                            Id = 11,
                            IsAvaiable = true,
                            MenuId = 6,
                            Name = "Churchkhela",
                            Price = 6.0m
                        },
                        new
                        {
                            Id = 12,
                            IsAvaiable = true,
                            MenuId = 6,
                            Name = "Honey Cake",
                            Price = 7.5m
                        },
                        new
                        {
                            Id = 13,
                            IsAvaiable = true,
                            MenuId = 7,
                            Name = "Lobio (Clay Pot)",
                            Price = 9.0m
                        },
                        new
                        {
                            Id = 14,
                            IsAvaiable = true,
                            MenuId = 7,
                            Name = "Lobio with Mchadi",
                            Price = 11.0m
                        },
                        new
                        {
                            Id = 15,
                            IsAvaiable = true,
                            MenuId = 8,
                            Name = "Pickled Vegetables",
                            Price = 5.5m
                        },
                        new
                        {
                            Id = 16,
                            IsAvaiable = true,
                            MenuId = 8,
                            Name = "Cornbread (Mchadi)",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 17,
                            IsAvaiable = true,
                            MenuId = 9,
                            Name = "Adjarian Khachapuri",
                            Price = 14.0m
                        },
                        new
                        {
                            Id = 18,
                            IsAvaiable = true,
                            MenuId = 9,
                            Name = "Imeretian Khachapuri",
                            Price = 12.0m
                        },
                        new
                        {
                            Id = 19,
                            IsAvaiable = true,
                            MenuId = 10,
                            Name = "Lemonade",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 20,
                            IsAvaiable = true,
                            MenuId = 10,
                            Name = "Beer",
                            Price = 6.5m
                        },
                        new
                        {
                            Id = 21,
                            IsAvaiable = true,
                            MenuId = 11,
                            Name = "Khinkali (10 pcs)",
                            Price = 13.0m
                        },
                        new
                        {
                            Id = 22,
                            IsAvaiable = true,
                            MenuId = 11,
                            Name = "Chakapuli",
                            Price = 18.0m
                        },
                        new
                        {
                            Id = 23,
                            IsAvaiable = true,
                            MenuId = 12,
                            Name = "Red Wine",
                            Price = 11.0m
                        },
                        new
                        {
                            Id = 24,
                            IsAvaiable = true,
                            MenuId = 12,
                            Name = "Cola",
                            Price = 3.0m
                        });
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Near Lisi Lake",
                            FirstName = "Nikoloz",
                            LastName = "Lortkipanidze",
                            Phone = "577711701"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address #2",
                            FirstName = "Temo",
                            LastName = "Totoshvili",
                            Phone = "577711702"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address #3",
                            FirstName = "Davit",
                            LastName = "Papava",
                            Phone = "577711703"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address #4",
                            FirstName = "Demetre",
                            LastName = "Kvirikashvili",
                            Phone = "577711704"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Address #5",
                            FirstName = "Saba",
                            LastName = "Dolidze",
                            Phone = "577711705"
                        });
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("StatusId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.ReservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Canceled"
                        });
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("SeatsPerTable")
                        .HasColumnType("int");

                    b.Property<int>("TotalTables")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Restaurants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Modern Georgian cuisine with creative twists and a cozy, artsy atmosphere.",
                            Email = "shavilomi@example.com",
                            Location = "Tbilisi, 30 Zurab Kvlividze St",
                            Name = "Shavi Lomi",
                            SeatsPerTable = 4,
                            TotalTables = 15
                        },
                        new
                        {
                            Id = 2,
                            Description = "Historic recipes from a 19th-century cookbook served in an elegant setting.",
                            Email = "barbarestan@example.com",
                            Location = "Tbilisi, 132 Davit Aghmashenebeli Ave",
                            Name = "Barbarestan",
                            SeatsPerTable = 4,
                            TotalTables = 12
                        },
                        new
                        {
                            Id = 3,
                            Description = "Charming garden restaurant known for traditional dishes and romantic vibes.",
                            Email = "ketoandkote@example.com",
                            Location = "Tbilisi, 3 Mikheil Zandukeli St",
                            Name = "Keto and Kote",
                            SeatsPerTable = 4,
                            TotalTables = 10
                        },
                        new
                        {
                            Id = 4,
                            Description = "Famous for authentic lobio and rustic Georgian comfort food.",
                            Email = "salobie@example.com",
                            Location = "Mtskheta, 1 Samtavro St",
                            Name = "Salobie Bia",
                            SeatsPerTable = 4,
                            TotalTables = 8
                        },
                        new
                        {
                            Id = 5,
                            Description = "Casual spot popular for Adjarian khachapuri and local favorites.",
                            Email = "machakhela@example.com",
                            Location = "Batumi, 26 May 6 St",
                            Name = "Machakhela",
                            SeatsPerTable = 4,
                            TotalTables = 14
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cozy restaurant offering classic Georgian meals in a warm setting.",
                            Email = "heartofbatumi@example.com",
                            Location = "Batumi, 11 Gen. Mazniashvili St",
                            Name = "Heart of Batumi",
                            SeatsPerTable = 4,
                            TotalTables = 12
                        });
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Worker"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.RoleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 1,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "nikusha191208@gmail.com",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PersonId = 1,
                            RegistrationDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "NikolozLortki"
                        },
                        new
                        {
                            Id = 2,
                            Email = "totoshvili@gmail.com",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PersonId = 2,
                            RegistrationDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Temo_totoshvili"
                        },
                        new
                        {
                            Id = 3,
                            Email = "papava@gmail.com",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PersonId = 3,
                            RegistrationDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "DatoPapava"
                        },
                        new
                        {
                            Id = 4,
                            Email = "kvirrik@gmail.com",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PersonId = 4,
                            RegistrationDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Kvirrik"
                        },
                        new
                        {
                            Id = 5,
                            Email = "SabaDolidze@gmail.com",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PersonId = 5,
                            RegistrationDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "SabaDolidze"
                        });
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Menu", b =>
                {
                    b.HasOne("Restaurant_Reservation_System.Data.Entities.Restaurant", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.MenuItem", b =>
                {
                    b.HasOne("Restaurant_Reservation_System.Data.Entities.Menu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Reservation", b =>
                {
                    b.HasOne("Restaurant_Reservation_System.Data.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Reservation_System.Data.Entities.Restaurant", "Restaurant")
                        .WithMany("Reservations")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Reservation_System.Data.Entities.ReservationStatus", "Status")
                        .WithMany("Reservations")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.RoleUser", b =>
                {
                    b.HasOne("Restaurant_Reservation_System.Data.Entities.Role", "Role")
                        .WithMany("RoleUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Reservation_System.Data.Entities.User", "User")
                        .WithMany("RoleUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.User", b =>
                {
                    b.HasOne("Restaurant_Reservation_System.Data.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("Restaurant_Reservation_System.Data.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Menu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.ReservationStatus", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Restaurant", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.Role", b =>
                {
                    b.Navigation("RoleUsers");
                });

            modelBuilder.Entity("Restaurant_Reservation_System.Data.Entities.User", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("RoleUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
